server:
  port: 9093
  servlet:
    context-path: /bidding-app/v1

spring:
  application:
    name: bidding-java-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}${MONGO_PASSWORD}@cluster0.q7znmio.mongodb.net/bidding-app
